<footer class="page-footer font-small blue fixed-bottom">
    <#--<div style="position:relative;overflow:hidden;"><a href="https://yandex.kz/maps/org/samoye_vlazhnoye_mesto_na_planete_zemlya/93615218902/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Самое влажное место на планете Земля</a><a href="https://yandex.kz/maps/114632/meghalaya/category/nature/20300558901/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:14px;">Природа в Мегхалая</a><iframe src="https://yandex.kz/map-widget/v1/-/CCU44Hg69A" width="560" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>-->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="/main"> Spring Airlines</a>
    </div>
</footer>